# Generated by Django 3.0.3 on 2020-02-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20200216_2341'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
