# Generated by Django 3.0.3 on 2020-02-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_auto_20200216_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.AlterModelTable(
            name='authusergroups',
            table=None,
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
