version: '3'
services: 
  backend: 
    build: ./city
    command: bash -c "python city/manage.py migrate && python city/manage.py runserver 127.0.0.1:8000"
    depends_on: 
      - db
    links: 
      - db
    ports: 
      - "8000:8000"
    restart: always
    volumes: 
      - ".:/city"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'citymysql'
      MYSQL_PASSWORD: 'stadtrundgang'
      MYSQL_ROOT_PASSWORD: 'stadtrundgang'
    ports: 
      - "3306:3306"
    restart: always
  frontend: 
    build: ./frontend
    #command: bash -c " cd frontend/FrontendPrototype && flutter doctor"
    depends_on: 
      - backend
    links: 
      - "db:db"
    ports: 
      - "8443:8443"
    restart: always
version: "3"
