version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'city-db'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/city
    links:
      - "db:db"
    ports:
      - "8000:8000"
    depends_on:
      - db