version: '3'
services: 
  backend: 
    build: ./backend
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on: 
      - db
    links: 
      - "db:db"
    ports: 
      - "8000:8000"
    restart: always
    volumes: 
      - ".:/city/backend"
  db: 
    environment: 
      MYSQL_DATABASE: city-db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
    image: "mysql:5.7"
    ports: 
      - "3306:3306"
    restart: always
  frontend: 
    build: ./frontend
    command: "npm start"
    depends_on: 
      - backend
    environment: 
      - NODE_ENV=development
    links: 
      - "db:db"
    ports: 
      - "3000:3000"
    restart: always
    volumes: 
      - "./frontend:/city/frontend"
version: "3"
