# Generated by Django 3.0.3 on 2020-02-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='n_media',
        ),
        migrations.AddField(
            model_name='landmark',
            name='latitude',
            field=models.FloatField(default=51.83),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landmark',
            name='longitude',
            field=models.FloatField(default=49.09733),
            preserve_default=False,
        ),
    ]
