# Generated by Django 3.0.3 on 2020-03-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200306_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=200, null=True)),
                ('body', models.CharField(max_length=4000)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='landmark',
            name='media',
            field=models.ManyToManyField(null=True, to='webapp.Media'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='text',
            field=models.ManyToManyField(null=True, to='webapp.TextBlock'),
        ),
    ]
