# Generated by Django 3.0.3 on 2020-02-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200228_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='namen', max_length=200),
            preserve_default=False,
        ),
    ]
