# Generated by Django 3.0.3 on 2020-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200326_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='landmark_id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='media_id',
        ),
        migrations.AlterField(
            model_name='landmark',
            name='media',
            field=models.ManyToManyField(blank=True, to='webapp.Media'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='text',
            field=models.ManyToManyField(blank=True, to='webapp.TextBlock'),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
