# Generated by Django 3.0.3 on 2020-02-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
